apiVersion: "nuclio.io/v1"
kind: NuclioFunction
metadata:
  name: telescope-receiver
  namespace: nuclio
spec:
  handler: "main:Handler"
  runtime: golang
  env:
    - name: MQTT_USERNAME
      value: guest
    - name: MQTT_PASSWORD
      value: guest
    - name: MQTT_BROKER_IP
      value: 192.168.1.20
    - name: PORT_ENV
      value: "5672"
    - name: AWS_ACCESS_KEY_ID
      value: "<your_access_key_id>"
    - name: AWS_SECRET_ACCESS_KEY
      value: "<your_secret_access_key>"
    - name: AWS_REGION
      value: "<your_region>"
  triggers:
    default-http:
      class: ""
      kind: http
      name: default-http
      maxWorkers: 1
    mqtt:
      class: ""
      kind: mqtt
      name: mqtt
      url: "192.168.1.20:1883"
      username: guest
      password: guest
      attributes:
        subscriptions:
          - qos: 2
            topic: iot/telescope