apiVersion: "nuclio.io/v1"
kind: NuclioFunction
metadata:
  name: probe-receiver
  namespace: nuclio
spec:
  handler: "main:Handler"
  runtime: golang
  env:
    - name: MQTT_USERNAME
      value: guest
    - name: MQTT_PASSWORD
      value: guest
    - name: MQTT_BROKER_IP
      value: 192.168.1.20
    - name: PORT_ENV
      value: "5672"
  triggers:
    default-http:
      class: ""
      kind: http
      name: default-http
      maxWorkers: 1
    mqtt:
      class: ""
      kind: mqtt
      name: mqtt
      url: "192.168.1.20:1883"
      username: guest
      password: guest
      attributes:
        subscriptions:
          - qos: 1
            topic: iot/probe/discover